cf_spec/fixtures/rails4_web_app/config/routes.rb
ANewHope::Application.routes.draw do
  resources :notes
  root 'notes#index'

  get 'env' => 'env#show'

  get 'browse' => 'browse#show'
  get 'browse/*path' => 'browse#show'

end

cf_spec/fixtures/rails4_web_app/app/models/note.rb
class Note < ActiveRecord::Base
end

cf_spec/fixtures/rails4_web_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cf_spec/fixtures/rails4_web_app/app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  def show
    path = "/#{params[:path]}"
    path += ".#{params[:format]}" if params[:format]

    begin
      if File.directory? path
        @dir = Dir.new(path)
        render
      else
        render :text => File.open(path).readlines.join("\n")
      end
    rescue Errno::ENOENT => e
      render text: "Failed with error: #{e}"
    end
  end
end

cf_spec/fixtures/rails4_web_app/app/controllers/env_controller.rb
class EnvController < ApplicationController
  def show
    @env = `env`
  end
end

cf_spec/fixtures/rails4_web_app/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body)
    end
end

cf_spec/fixtures/rails4_web_app/app/helpers/application_helper.rb
module ApplicationHelper
end

cf_spec/fixtures/rails4_web_app/app/helpers/notes_helper.rb
module NotesHelper
end

cf_spec/fixtures/rails4_web_app/app/views/browse/show.html.erb
<ul>
  <% @dir.sort.each do |node| %>
    <% file = File.join(@dir,node) %>
    <li>
      <%= link_to node, "/browse#{File.absolute_path(file)}" %>
    </li>
  <% end %>
</ul>

cf_spec/fixtures/rails4_web_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ANewHope</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>The Kessel Run</h1>

<ul>
  <li>
    <%= link_to 'Browse File System', :browse %>
  </li>
  <li>
    <%= link_to 'View Environment', :env %>
  </li>
  <li>
    <%= link_to 'Notes', :notes %>
  </li>
</ul>


<%= yield %>

</body>
</html>

cf_spec/fixtures/rails4_web_app/app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

cf_spec/fixtures/rails4_web_app/app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

cf_spec/fixtures/rails4_web_app/app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

cf_spec/fixtures/rails4_web_app/app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

cf_spec/fixtures/rails4_web_app/app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>